/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg01_1_siddha_system_1_4_1;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeError.printStackTrace;

/**
 *
 * @author CHETHANA
 */
public class add extends javax.swing.JFrame {
UniversalMethod u = new UniversalMethod();
public static int idsearch;

    /**
     * Creates new form add
     */
    public add() {
        initComponents();
        u.imageMethod(background, home_la_uesr_image);
       UniversalMethod.TimeMethod(agent_la_date, agent_la_time);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agent_la_date = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        agent_la_time = new javax.swing.JLabel();
        home_la_uesr_image = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        agent_la_home_img = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        login_la_mini = new javax.swing.JLabel();
        login_la_cloce = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_ = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        w1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        nic1 = new javax.swing.JTextField();
        search_ = new javax.swing.JLabel();
        update_ = new javax.swing.JLabel();
        enter_ = new javax.swing.JLabel();
        clear_ = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        n2 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        a2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        nic2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        w2 = new javax.swing.JTextField();
        nic3 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        a3 = new javax.swing.JTextField();
        n3 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        w3 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        n4 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        a4 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        nic4 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        w4 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1376, 768));
        setUndecorated(true);
        getContentPane().setLayout(null);

        agent_la_date.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agent_la_date.setForeground(new java.awt.Color(255, 255, 255));
        agent_la_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agent_la_date.setText("Invoice");
        agent_la_date.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(agent_la_date);
        agent_la_date.setBounds(10, 5, 130, 35);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(140, 5, 20, 30);

        agent_la_time.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agent_la_time.setForeground(new java.awt.Color(255, 255, 255));
        agent_la_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agent_la_time.setText("Invoice");
        agent_la_time.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(agent_la_time);
        agent_la_time.setBounds(150, 5, 130, 35);

        home_la_uesr_image.setForeground(new java.awt.Color(0, 0, 0));
        home_la_uesr_image.setText("userlogo");
        getContentPane().add(home_la_uesr_image);
        home_la_uesr_image.setBounds(290, 10, 30, 30);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(280, 5, 20, 30);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(580, 5, 20, 30);

        agent_la_home_img.setBackground(new java.awt.Color(0, 0, 0));
        agent_la_home_img.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        agent_la_home_img.setForeground(new java.awt.Color(255, 255, 255));
        agent_la_home_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agent_la_home_img.setText("Dash Board");
        agent_la_home_img.setOpaque(true);
        agent_la_home_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseExited(evt);
            }
        });
        getContentPane().add(agent_la_home_img);
        agent_la_home_img.setBounds(600, 5, 100, 30);

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD COUPON");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(760, 1, 330, 40);

        login_la_mini.setBackground(new java.awt.Color(0, 0, 0));
        login_la_mini.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        login_la_mini.setForeground(new java.awt.Color(255, 255, 255));
        login_la_mini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_la_mini.setText("-");
        login_la_mini.setBorder(new javax.swing.border.MatteBorder(null));
        login_la_mini.setOpaque(true);
        login_la_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_la_miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_la_miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_la_miniMouseExited(evt);
            }
        });
        getContentPane().add(login_la_mini);
        login_la_mini.setBounds(1295, 10, 30, 30);

        login_la_cloce.setBackground(new java.awt.Color(0, 0, 0));
        login_la_cloce.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        login_la_cloce.setForeground(new java.awt.Color(255, 255, 255));
        login_la_cloce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_la_cloce.setText("x");
        login_la_cloce.setBorder(new javax.swing.border.MatteBorder(null));
        login_la_cloce.setOpaque(true);
        login_la_cloce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseExited(evt);
            }
        });
        getContentPane().add(login_la_cloce);
        login_la_cloce.setBounds(1330, 10, 30, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Coupon ID");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(440, 60, 120, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(":");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(560, 60, 30, 30);

        id_.setBackground(new java.awt.Color(255, 255, 255));
        id_.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        id_.setForeground(new java.awt.Color(0, 0, 0));
        id_.setText(" ");
        id_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                id_KeyPressed(evt);
            }
        });
        getContentPane().add(id_);
        id_.setBounds(590, 60, 210, 33);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Name 01");
        jLabel24.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel24);
        jLabel24.setBounds(30, 120, 160, 30);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText(":");
        jLabel29.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel29);
        jLabel29.setBounds(190, 120, 30, 30);

        n1.setBackground(new java.awt.Color(255, 255, 255));
        n1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        n1.setForeground(new java.awt.Color(0, 0, 0));
        n1.setText("Name1");
        n1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                n1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                n1FocusLost(evt);
            }
        });
        n1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                n1KeyPressed(evt);
            }
        });
        getContentPane().add(n1);
        n1.setBounds(210, 120, 700, 33);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Contact Number ");
        jLabel26.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel26);
        jLabel26.setBounds(520, 200, 160, 30);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText(":");
        jLabel27.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel27);
        jLabel27.setBounds(680, 200, 30, 30);

        t1.setBackground(new java.awt.Color(255, 255, 255));
        t1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        t1.setForeground(new java.awt.Color(0, 0, 0));
        t1.setText("0000000000");
        t1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t1FocusLost(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(700, 200, 220, 33);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Address");
        jLabel25.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel25);
        jLabel25.setBounds(30, 160, 160, 30);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText(":");
        jLabel28.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel28);
        jLabel28.setBounds(190, 160, 30, 30);

        a1.setBackground(new java.awt.Color(255, 255, 255));
        a1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        a1.setForeground(new java.awt.Color(0, 0, 0));
        a1.setText("Address");
        a1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                a1FocusLost(evt);
            }
        });
        a1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a1KeyPressed(evt);
            }
        });
        getContentPane().add(a1);
        a1.setBounds(210, 160, 1150, 33);

        jLabel34.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Whatsapp Number ");
        jLabel34.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel34);
        jLabel34.setBounds(950, 200, 170, 30);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText(":");
        jLabel35.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel35);
        jLabel35.setBounds(1120, 200, 30, 30);

        w1.setBackground(new java.awt.Color(255, 255, 255));
        w1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        w1.setForeground(new java.awt.Color(0, 0, 0));
        w1.setText("0000000000");
        w1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                w1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                w1FocusLost(evt);
            }
        });
        w1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                w1KeyPressed(evt);
            }
        });
        getContentPane().add(w1);
        w1.setBounds(1140, 200, 220, 33);

        jLabel32.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("NIC Number");
        jLabel32.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel32);
        jLabel32.setBounds(30, 200, 160, 30);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(":");
        jLabel31.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel31);
        jLabel31.setBounds(190, 200, 30, 30);

        nic1.setBackground(new java.awt.Color(255, 255, 255));
        nic1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nic1.setForeground(new java.awt.Color(0, 0, 0));
        nic1.setText("NIC");
        nic1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nic1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nic1FocusLost(evt);
            }
        });
        nic1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nic1KeyPressed(evt);
            }
        });
        getContentPane().add(nic1);
        nic1.setBounds(210, 200, 250, 33);

        search_.setBackground(new java.awt.Color(0, 0, 0));
        search_.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        search_.setForeground(new java.awt.Color(255, 255, 255));
        search_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_.setText("Search");
        search_.setOpaque(true);
        search_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search_MouseExited(evt);
            }
        });
        getContentPane().add(search_);
        search_.setBounds(390, 660, 190, 35);

        update_.setBackground(new java.awt.Color(0, 0, 0));
        update_.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        update_.setForeground(new java.awt.Color(255, 255, 255));
        update_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update_.setText("Update");
        update_.setOpaque(true);
        update_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                update_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                update_MouseExited(evt);
            }
        });
        getContentPane().add(update_);
        update_.setBounds(620, 660, 200, 35);

        enter_.setBackground(new java.awt.Color(0, 0, 0));
        enter_.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        enter_.setForeground(new java.awt.Color(255, 255, 255));
        enter_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter_.setText("Enter");
        enter_.setOpaque(true);
        enter_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enter_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enter_MouseExited(evt);
            }
        });
        getContentPane().add(enter_);
        enter_.setBounds(1140, 660, 210, 35);

        clear_.setBackground(new java.awt.Color(0, 0, 0));
        clear_.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        clear_.setForeground(new java.awt.Color(255, 255, 255));
        clear_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clear_.setText("Clear");
        clear_.setOpaque(true);
        clear_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clear_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clear_MouseExited(evt);
            }
        });
        getContentPane().add(clear_);
        clear_.setBounds(870, 660, 190, 35);

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(10, 630, 1370, 10);

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(0, 240, 1370, 10);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(0, 40, 1370, 10);

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(10, 100, 1370, 10);

        jLabel30.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Name 02");
        jLabel30.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel30);
        jLabel30.setBounds(20, 250, 160, 30);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText(":");
        jLabel33.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel33);
        jLabel33.setBounds(180, 250, 30, 30);

        n2.setBackground(new java.awt.Color(255, 255, 255));
        n2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        n2.setForeground(new java.awt.Color(0, 0, 0));
        n2.setText("Name2");
        n2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                n2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                n2FocusLost(evt);
            }
        });
        n2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                n2KeyPressed(evt);
            }
        });
        getContentPane().add(n2);
        n2.setBounds(200, 250, 700, 33);

        jLabel36.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Address");
        jLabel36.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel36);
        jLabel36.setBounds(20, 290, 160, 30);

        jLabel37.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText(":");
        jLabel37.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel37);
        jLabel37.setBounds(180, 290, 30, 30);

        a2.setBackground(new java.awt.Color(255, 255, 255));
        a2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        a2.setForeground(new java.awt.Color(0, 0, 0));
        a2.setText("Address");
        a2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                a2FocusLost(evt);
            }
        });
        a2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a2KeyPressed(evt);
            }
        });
        getContentPane().add(a2);
        a2.setBounds(200, 290, 1150, 33);

        jLabel38.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("NIC Number");
        jLabel38.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel38);
        jLabel38.setBounds(20, 330, 160, 30);

        jLabel39.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText(":");
        jLabel39.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel39);
        jLabel39.setBounds(180, 330, 30, 30);

        nic2.setBackground(new java.awt.Color(255, 255, 255));
        nic2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nic2.setForeground(new java.awt.Color(0, 0, 0));
        nic2.setText("NIC");
        nic2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nic2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nic2FocusLost(evt);
            }
        });
        nic2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nic2KeyPressed(evt);
            }
        });
        getContentPane().add(nic2);
        nic2.setBounds(200, 330, 250, 33);

        jLabel40.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Contact Number ");
        jLabel40.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel40);
        jLabel40.setBounds(510, 330, 160, 30);

        jLabel41.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText(":");
        jLabel41.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel41);
        jLabel41.setBounds(670, 330, 30, 30);

        t2.setBackground(new java.awt.Color(255, 255, 255));
        t2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        t2.setForeground(new java.awt.Color(0, 0, 0));
        t2.setText("0000000000");
        t2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t2FocusLost(evt);
            }
        });
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(690, 330, 220, 33);

        jLabel42.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Whatsapp Number ");
        jLabel42.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel42);
        jLabel42.setBounds(940, 330, 170, 30);

        jLabel43.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText(":");
        jLabel43.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel43);
        jLabel43.setBounds(1110, 330, 30, 30);

        w2.setBackground(new java.awt.Color(255, 255, 255));
        w2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        w2.setForeground(new java.awt.Color(0, 0, 0));
        w2.setText("0000000000");
        w2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                w2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                w2FocusLost(evt);
            }
        });
        w2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                w2KeyPressed(evt);
            }
        });
        getContentPane().add(w2);
        w2.setBounds(1130, 330, 220, 33);

        nic3.setBackground(new java.awt.Color(255, 255, 255));
        nic3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nic3.setForeground(new java.awt.Color(0, 0, 0));
        nic3.setText("NIC");
        nic3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nic3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nic3FocusLost(evt);
            }
        });
        nic3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nic3KeyPressed(evt);
            }
        });
        getContentPane().add(nic3);
        nic3.setBounds(200, 460, 250, 33);

        jLabel44.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText(":");
        jLabel44.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel44);
        jLabel44.setBounds(180, 460, 30, 30);

        jLabel45.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("NIC Number");
        jLabel45.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel45);
        jLabel45.setBounds(20, 460, 160, 30);

        jLabel46.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Address");
        jLabel46.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel46);
        jLabel46.setBounds(20, 420, 160, 30);

        jLabel47.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText(":");
        jLabel47.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel47);
        jLabel47.setBounds(180, 420, 30, 30);

        a3.setBackground(new java.awt.Color(255, 255, 255));
        a3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        a3.setForeground(new java.awt.Color(0, 0, 0));
        a3.setText("Address");
        a3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                a3FocusLost(evt);
            }
        });
        a3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a3KeyPressed(evt);
            }
        });
        getContentPane().add(a3);
        a3.setBounds(200, 420, 1150, 33);

        n3.setBackground(new java.awt.Color(255, 255, 255));
        n3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        n3.setForeground(new java.awt.Color(0, 0, 0));
        n3.setText("Name3");
        n3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                n3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                n3FocusLost(evt);
            }
        });
        n3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                n3KeyPressed(evt);
            }
        });
        getContentPane().add(n3);
        n3.setBounds(200, 380, 700, 33);

        jLabel48.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText(":");
        jLabel48.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel48);
        jLabel48.setBounds(180, 380, 30, 30);

        jLabel49.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Name 03");
        jLabel49.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel49);
        jLabel49.setBounds(20, 380, 160, 30);

        jLabel50.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Contact Number ");
        jLabel50.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel50);
        jLabel50.setBounds(510, 460, 160, 30);

        jLabel51.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText(":");
        jLabel51.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel51);
        jLabel51.setBounds(670, 460, 30, 30);

        t3.setBackground(new java.awt.Color(255, 255, 255));
        t3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        t3.setForeground(new java.awt.Color(0, 0, 0));
        t3.setText("0000000000");
        t3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t3FocusLost(evt);
            }
        });
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t3KeyPressed(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(690, 460, 220, 33);

        jLabel52.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Whatsapp Number ");
        jLabel52.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel52);
        jLabel52.setBounds(940, 460, 170, 30);

        jLabel53.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText(":");
        jLabel53.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel53);
        jLabel53.setBounds(1110, 460, 30, 30);

        w3.setBackground(new java.awt.Color(255, 255, 255));
        w3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        w3.setForeground(new java.awt.Color(0, 0, 0));
        w3.setText("0000000000");
        w3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                w3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                w3FocusLost(evt);
            }
        });
        w3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                w3KeyPressed(evt);
            }
        });
        getContentPane().add(w3);
        w3.setBounds(1130, 460, 220, 33);

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(0, 370, 1370, 10);

        n4.setBackground(new java.awt.Color(255, 255, 255));
        n4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        n4.setForeground(new java.awt.Color(0, 0, 0));
        n4.setText("Name4");
        n4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                n4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                n4FocusLost(evt);
            }
        });
        n4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                n4KeyPressed(evt);
            }
        });
        getContentPane().add(n4);
        n4.setBounds(200, 510, 700, 33);

        jLabel54.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText(":");
        jLabel54.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel54);
        jLabel54.setBounds(180, 510, 30, 30);

        jLabel55.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText(" Name 04");
        jLabel55.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel55);
        jLabel55.setBounds(20, 510, 160, 30);

        jLabel56.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Address");
        jLabel56.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel56);
        jLabel56.setBounds(20, 550, 160, 30);

        jLabel57.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText(":");
        jLabel57.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel57);
        jLabel57.setBounds(180, 550, 30, 30);

        a4.setBackground(new java.awt.Color(255, 255, 255));
        a4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        a4.setForeground(new java.awt.Color(0, 0, 0));
        a4.setText("Address");
        a4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                a4FocusLost(evt);
            }
        });
        a4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a4KeyPressed(evt);
            }
        });
        getContentPane().add(a4);
        a4.setBounds(200, 550, 1150, 33);

        jLabel58.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("NIC Number");
        jLabel58.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel58);
        jLabel58.setBounds(20, 590, 160, 30);

        jLabel59.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText(":");
        jLabel59.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel59);
        jLabel59.setBounds(180, 590, 30, 30);

        nic4.setBackground(new java.awt.Color(255, 255, 255));
        nic4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nic4.setForeground(new java.awt.Color(0, 0, 0));
        nic4.setText("NIC");
        nic4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nic4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nic4FocusLost(evt);
            }
        });
        nic4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nic4KeyPressed(evt);
            }
        });
        getContentPane().add(nic4);
        nic4.setBounds(200, 590, 250, 33);

        jLabel60.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Contact Number ");
        jLabel60.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel60);
        jLabel60.setBounds(510, 590, 160, 30);

        jLabel61.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 0, 0));
        jLabel61.setText(":");
        jLabel61.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel61);
        jLabel61.setBounds(670, 590, 30, 30);

        t4.setBackground(new java.awt.Color(255, 255, 255));
        t4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        t4.setForeground(new java.awt.Color(0, 0, 0));
        t4.setText("0000000000");
        t4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t4FocusLost(evt);
            }
        });
        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t4KeyPressed(evt);
            }
        });
        getContentPane().add(t4);
        t4.setBounds(690, 590, 220, 33);

        jLabel62.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Whatsapp Number ");
        jLabel62.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel62);
        jLabel62.setBounds(940, 590, 170, 30);

        jLabel63.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText(":");
        jLabel63.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel63);
        jLabel63.setBounds(1110, 590, 30, 30);

        w4.setBackground(new java.awt.Color(255, 255, 255));
        w4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        w4.setForeground(new java.awt.Color(0, 0, 0));
        w4.setText("0000000000");
        w4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                w4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                w4FocusLost(evt);
            }
        });
        w4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                w4KeyPressed(evt);
            }
        });
        getContentPane().add(w4);
        w4.setBounds(1130, 590, 220, 33);

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator10);
        jSeparator10.setBounds(0, 500, 1370, 10);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "ID"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 650, 340, 100);

        background.setBackground(new java.awt.Color(234, 232, 232));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 1380, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agent_la_home_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseClicked
        m(agent_la_home_img,2);
        int x = JOptionPane.showConfirmDialog(this, "Do you sure Go to The Home ?", "Change Interface", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.YES_OPTION == x) {
                dashboard.getCallPopup().setVisible(true);
                this.dispose();
            } else if (JOptionPane.NO_OPTION == x) {
                setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                id_.grabFocus();
            }
        
    }//GEN-LAST:event_agent_la_home_imgMouseClicked

    private void agent_la_home_imgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseEntered
        m(agent_la_home_img,0); //  u.imageMethod("/img/homeB2.png", agent_la_home_img);
    }//GEN-LAST:event_agent_la_home_imgMouseEntered

    private void agent_la_home_imgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseExited
        m(agent_la_home_img,1); //    u.imageMethod("/img/homeB1.png", agent_la_home_img);
    }//GEN-LAST:event_agent_la_home_imgMouseExited

    private void login_la_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseClicked
        m( login_la_mini,2); //
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_login_la_miniMouseClicked

    private void login_la_miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseEntered
        //    login_la_mini.setBackground(Color.gray);
        m( login_la_mini,0); //  u.imageMethod("/img/mini2.png", login_la_mini);
    }//GEN-LAST:event_login_la_miniMouseEntered

    private void login_la_miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseExited
        //    login_la_mini.setBackground(Color.white);
        m( login_la_mini,1); //   u.imageMethod("/img/mini.png", login_la_mini);
    }//GEN-LAST:event_login_la_miniMouseExited

    private void login_la_cloceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseClicked
        m( login_la_cloce,2); //
        SystemClose();
    }//GEN-LAST:event_login_la_cloceMouseClicked

    private void login_la_cloceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseEntered
        //    login_la_cloce.setBackground(Color.red);
        m( login_la_cloce,0); //   u.imageMethod("/img/exti.png", login_la_cloce);
    }//GEN-LAST:event_login_la_cloceMouseEntered

    private void login_la_cloceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseExited
        //    login_la_cloce.setBackground(Color.white);
        m( login_la_cloce,1); //   u.imageMethod("/img/exti2.png", login_la_cloce);
    }//GEN-LAST:event_login_la_cloceMouseExited

    private void id_KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
         u.grabFocusMethod(evt, id_, n1);
        }else{
            txValidateKeyEvent(evt, id_, "N", 9);
        }
    }//GEN-LAST:event_id_KeyPressed

    private void n1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, n1, a1);
        }else{
            txValidateKeyEvent(evt,  n1, "NA", 55);
        }
    }//GEN-LAST:event_n1KeyPressed

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, t1,  w1);
        }else{
            txValidateKeyEvent(evt, t1, "N", 13);
        }
    }//GEN-LAST:event_t1KeyPressed

    private void a1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, a1,  nic1);
        } else {
            txValidateKeyEvent(evt,  a1, "NA", 160);
        }
    }//GEN-LAST:event_a1KeyPressed

    private void w1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_w1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
       u.grabFocusMethod(evt,  w1, n2);
        } else {
            txValidateKeyEvent(evt,  w1, "N", 10);
        }
    }//GEN-LAST:event_w1KeyPressed

    private void nic1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nic1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt,  nic1, t1);
        } else {
            txValidateKeyEvent(evt,  nic1, "NIC", 10);
        }
    }//GEN-LAST:event_nic1KeyPressed

    private void search_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_MouseClicked
        m(search_,2); //  u.imageMethod("/img/search2.png", cal_rx_la_search );
        if (!id_.getText().isEmpty()) {
            idsearch = Integer.parseInt(id_.getText());
             searchEMP();
        } else {
            JOptionPane.showMessageDialog(null, "Error Not Selected The ID  !!! \n searchEMP() \n" , "Error Massage", JOptionPane.ERROR_MESSAGE);
            id_.grabFocus();
        }
    }//GEN-LAST:event_search_MouseClicked

    private void search_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_MouseEntered
        m(search_,0);  // u.imageMethod("/img/search2.png", cal_rx_la_search );
    }//GEN-LAST:event_search_MouseEntered

    private void search_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_MouseExited
        m(search_,1); //  u.imageMethod("/img/search.png", cal_rx_la_search );
    }//GEN-LAST:event_search_MouseExited

    private void update_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_MouseClicked
        m(update_,2); //    u.imageMethod("/img/update2.png", cal_rx_la_update );
        if (idsearch == 0) {
            JOptionPane.showMessageDialog(this, "Please Select the RX", "Not Selected", JOptionPane.OK_OPTION);
        } else {
         updateRX_idrx();
        }
    }//GEN-LAST:event_update_MouseClicked

    private void update_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_MouseEntered
        m(update_,0); //    u.imageMethod("/img/update2.png", cal_rx_la_update );
    }//GEN-LAST:event_update_MouseEntered

    private void update_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_MouseExited
        m(update_,1); //   u.imageMethod("/img/update.png", cal_rx_la_update );
    }//GEN-LAST:event_update_MouseExited

    private void enter_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter_MouseClicked
        m(enter_,2); //   u.imageMethod("/img/enter2.png", cal_rx_la_enter );
       emterMouseClickMethod();
    }//GEN-LAST:event_enter_MouseClicked

    private void enter_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter_MouseEntered
        m(enter_,0); //   u.imageMethod("/img/enter2.png", cal_rx_la_enter );
    }//GEN-LAST:event_enter_MouseEntered

    private void enter_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter_MouseExited
        m(enter_,1); //   u.imageMethod("/img/enter.png", cal_rx_la_enter );
    }//GEN-LAST:event_enter_MouseExited

    private void clear_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_MouseClicked
        m(clear_,2); //    u.imageMethod("/img/clrearB2.png", cal_rx_la_new);
       cleareFields();
    }//GEN-LAST:event_clear_MouseClicked

    private void clear_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_MouseEntered
        m(clear_,0); //   u.imageMethod("/img/clrearB2.png", cal_rx_la_new);
    }//GEN-LAST:event_clear_MouseEntered

    private void clear_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_MouseExited
        m(clear_,1); //     u.imageMethod("/img/clrearB1.png", cal_rx_la_new);
    }//GEN-LAST:event_clear_MouseExited

    private void n2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n2KeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, n2, a2);
        }else{
            txValidateKeyEvent(evt,  n2, "NA", 55);
        }
    }//GEN-LAST:event_n2KeyPressed

    private void a2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a2KeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, a2,  nic2);
        } else {
            txValidateKeyEvent(evt,  a2, "NA", 160);
        }
    }//GEN-LAST:event_a2KeyPressed

    private void nic2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nic2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt,  nic2, t2);
        } else {
            txValidateKeyEvent(evt,  nic2, "NIC", 10);
        }
    }//GEN-LAST:event_nic2KeyPressed

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, t2,  w2);
        }else{
            txValidateKeyEvent(evt, t2, "N", 13);
        }
    }//GEN-LAST:event_t2KeyPressed

    private void w2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_w2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
       u.grabFocusMethod(evt,  w2, n3);
        } else {
            txValidateKeyEvent(evt,  w2, "N", 10);
        }
    }//GEN-LAST:event_w2KeyPressed

    private void nic3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nic3KeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt,  nic3, t3);
        } else {
            txValidateKeyEvent(evt,  nic3, "NIC", 10);
        }
    }//GEN-LAST:event_nic3KeyPressed

    private void a3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a3KeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, a3,  nic3);
        } else {
            txValidateKeyEvent(evt,  a3, "NA", 160);
        }
    }//GEN-LAST:event_a3KeyPressed

    private void n3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n3KeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, n3, a3);
        }else{
            txValidateKeyEvent(evt,  n3, "NA", 55);
        }
    }//GEN-LAST:event_n3KeyPressed

    private void t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, t3,  w3);
        }else{
            txValidateKeyEvent(evt, t3, "N", 13);
        }
    }//GEN-LAST:event_t3KeyPressed

    private void w3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_w3KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
       u.grabFocusMethod(evt,  w3, n4);
        } else {
            txValidateKeyEvent(evt,  w3, "N", 10);
        }
    }//GEN-LAST:event_w3KeyPressed

    private void n4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n4KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, n4, a4);
        }else{
            txValidateKeyEvent(evt,  n4, "NA", 55);
        }
    }//GEN-LAST:event_n4KeyPressed

    private void a4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a4KeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, a4,  nic4);
        } else {
            txValidateKeyEvent(evt,  a4, "NA", 160);
        }
    }//GEN-LAST:event_a4KeyPressed

    private void nic4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nic4KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt,  nic4, t4);
        } else {
            txValidateKeyEvent(evt,  nic4, "NIC", 10);
        }
    }//GEN-LAST:event_nic4KeyPressed

    private void t4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, t4,  w4);
        }else{
            txValidateKeyEvent(evt, t4, "N", 13);
        }
    }//GEN-LAST:event_t4KeyPressed

    private void w4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_w4KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
       u.grabFocusMethod(evt,  w4, enter_);
        } else {
            txValidateKeyEvent(evt,  w4, "N", 10);
        }
    }//GEN-LAST:event_w4KeyPressed

    private void n1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_n1FocusGained
       if(n1.getText().equals("Name1")){
           n1.setText("");
       }
    }//GEN-LAST:event_n1FocusGained

    private void n1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_n1FocusLost
        if(n1.getText().equals("")){
           n1.setText("Name1");
       }
    }//GEN-LAST:event_n1FocusLost

    private void a1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a1FocusGained
        if(a1.getText().equals("Address")){
           a1.setText("");
       }
    }//GEN-LAST:event_a1FocusGained

    private void a1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a1FocusLost
         if(a1.getText().equals("")){
           a1.setText("Address");
         }
    }//GEN-LAST:event_a1FocusLost

    private void nic1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nic1FocusGained
       if(nic1.getText().equals("NIC")){
           nic1.setText("");
       }
    }//GEN-LAST:event_nic1FocusGained

    private void t1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusGained
       if(t1.getText().equals("0000000000")){
           t1.setText("");
       }
    }//GEN-LAST:event_t1FocusGained

    private void nic1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nic1FocusLost
        if(nic1.getText().equals("")){
           nic1.setText("NIC");
       }
    }//GEN-LAST:event_nic1FocusLost

    private void t1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusLost
        if(t1.getText().equals("")){
           t1.setText("0000000000");
       }
    }//GEN-LAST:event_t1FocusLost

    private void w1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_w1FocusGained
         if(w1.getText().equals("0000000000")){
           w1.setText("");
       }
    }//GEN-LAST:event_w1FocusGained

    private void w1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_w1FocusLost
        if(w1.getText().equals("")){
           w1.setText("0000000000");
       }
    }//GEN-LAST:event_w1FocusLost

    private void n2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_n2FocusGained
       if(n2.getText().equals("Name2")){
           n2.setText("");
       }
    }//GEN-LAST:event_n2FocusGained

    private void n2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_n2FocusLost
        if(n2.getText().equals("")){
           n2.setText("Name2");
       }
    }//GEN-LAST:event_n2FocusLost

    private void n3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_n3FocusGained
      if(n3.getText().equals("Name3")){
           n3.setText("");
       }
    }//GEN-LAST:event_n3FocusGained

    private void n3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_n3FocusLost
       if(n3.getText().equals("")){
           n3.setText("Name3");
       }
    }//GEN-LAST:event_n3FocusLost

    private void n4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_n4FocusGained
      if(n4.getText().equals("Name4")){
           n4.setText("");
       }
    }//GEN-LAST:event_n4FocusGained

    private void n4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_n4FocusLost
        if(n4.getText().equals("")){
           n4.setText("Name4");
       }
    }//GEN-LAST:event_n4FocusLost

    private void a2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a2FocusGained
        if(a2.getText().equals("Address")){
           a2.setText("");
       }
    }//GEN-LAST:event_a2FocusGained

    private void a3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a3FocusGained
         if(a3.getText().equals("Address")){
           a3.setText("");
       }
    }//GEN-LAST:event_a3FocusGained

    private void a4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a4FocusGained
        if(a4.getText().equals("Address")){
           a4.setText("");
       }
    }//GEN-LAST:event_a4FocusGained

    private void a2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a2FocusLost
        if(a2.getText().equals("")){
           a2.setText("Address");
         }
    }//GEN-LAST:event_a2FocusLost

    private void a3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a3FocusLost
        if(a3.getText().equals("")){
           a3.setText("Address");
         }
    }//GEN-LAST:event_a3FocusLost

    private void a4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a4FocusLost
       if(a4.getText().equals("")){
           a4.setText("Address");
         }
    }//GEN-LAST:event_a4FocusLost

    private void nic2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nic2FocusGained
       if(nic2.getText().equals("NIC")){
           nic2.setText("");
       }
    }//GEN-LAST:event_nic2FocusGained

    private void nic3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nic3FocusGained
        if(nic3.getText().equals("NIC")){
           nic3.setText("");
       }
    }//GEN-LAST:event_nic3FocusGained

    private void nic4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nic4FocusGained
        if(nic4.getText().equals("NIC")){
           nic4.setText("");
       }
    }//GEN-LAST:event_nic4FocusGained

    private void nic2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nic2FocusLost
        if(nic2.getText().equals("")){
           nic2.setText("NIC");
       }
    }//GEN-LAST:event_nic2FocusLost

    private void nic3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nic3FocusLost
        if(nic3.getText().equals("")){
           nic3.setText("NIC");
       }
    }//GEN-LAST:event_nic3FocusLost

    private void nic4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nic4FocusLost
        if(nic4.getText().equals("")){
           nic4.setText("NIC");
       }
    }//GEN-LAST:event_nic4FocusLost

    private void t2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t2FocusGained
       if(t2.getText().equals("0000000000")){
           t2.setText("");
       }
    }//GEN-LAST:event_t2FocusGained

    private void t3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t3FocusGained
        if(t3.getText().equals("0000000000")){
           t3.setText("");
       }
    }//GEN-LAST:event_t3FocusGained

    private void t4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t4FocusGained
        if(t4.getText().equals("0000000000")){
           t4.setText("");
       }
    }//GEN-LAST:event_t4FocusGained

    private void t2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t2FocusLost
        if(t2.getText().equals("")){
           t2.setText("0000000000");
       }
    }//GEN-LAST:event_t2FocusLost

    private void t3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t3FocusLost
        if(t3.getText().equals("")){
           t3.setText("0000000000");
       }
    }//GEN-LAST:event_t3FocusLost

    private void t4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t4FocusLost
        if(t4.getText().equals("")){
           t4.setText("0000000000");
       }
    }//GEN-LAST:event_t4FocusLost

    private void w2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_w2FocusGained
        if(w2.getText().equals("0000000000")){
           w2.setText("");
       }
    }//GEN-LAST:event_w2FocusGained

    private void w3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_w3FocusGained
         if(w3.getText().equals("0000000000")){
           w3.setText("");
       }
    }//GEN-LAST:event_w3FocusGained

    private void w4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_w4FocusGained
         if(w4.getText().equals("0000000000")){
           w4.setText("");
       }
    }//GEN-LAST:event_w4FocusGained

    private void w2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_w2FocusLost
        if(w2.getText().equals("")){
           w2.setText("0000000000");
       }
    }//GEN-LAST:event_w2FocusLost

    private void w3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_w3FocusLost
       if(w3.getText().equals("")){
           w3.setText("0000000000");
       }
    }//GEN-LAST:event_w3FocusLost

    private void w4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_w4FocusLost
       if(w4.getText().equals("")){
           w4.setText("0000000000");
       }
    }//GEN-LAST:event_w4FocusLost

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel defTabMod = (DefaultTableModel) jTable1.getModel();
        idsearch = Integer.parseInt(defTabMod.getValueAt(jTable1.getSelectedRow(), 1).toString());
        id_.setText(defTabMod.getValueAt(jTable1.getSelectedRow(), 1).toString());
        searchEMP();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new add().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JLabel agent_la_date;
    private javax.swing.JLabel agent_la_home_img;
    private javax.swing.JLabel agent_la_time;
    private javax.swing.JLabel background;
    private javax.swing.JLabel clear_;
    private javax.swing.JLabel enter_;
    private javax.swing.JLabel home_la_uesr_image;
    private javax.swing.JTextField id_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel login_la_cloce;
    private javax.swing.JLabel login_la_mini;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTextField n4;
    private javax.swing.JTextField nic1;
    private javax.swing.JTextField nic2;
    private javax.swing.JTextField nic3;
    private javax.swing.JTextField nic4;
    private javax.swing.JLabel search_;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JLabel update_;
    private javax.swing.JTextField w1;
    private javax.swing.JTextField w2;
    private javax.swing.JTextField w3;
    private javax.swing.JTextField w4;
    // End of variables declaration//GEN-END:variables

  public void m(JLabel lable,int T){
    if(T==0){//en
     lable.setBackground(new Color(255, 170, 0));
    }else if(T==1){//ex
        lable.setBackground(new Color(0, 0, 0));
    }else if(T==2){//cl
        lable.setBackground(new Color(0, 255, 251));
    }
}
   void SystemClose() {
        int x = JOptionPane.showConfirmDialog(this, "Do you sure close the System ?", "Exit System", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == x) {
            // setDefaultCloseOperation(EXIT_ON_CLOSE);
            System.exit(0);
        } else if (JOptionPane.NO_OPTION == x) {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            login_la_cloce.setBackground(new Color(153, 204, 255));
        }
    }
   
 private void txValidateKeyEvent(KeyEvent evt, JTextField txName, String txType, int lenthNeedFeld) {

        int iNumber = evt.getKeyCode();
        if (txName.getText().length() <= lenthNeedFeld) {
              if (txType.equals("NIC")) {
                if (txName.getText().length() == 9) {
                    if ((iNumber == 86)) {
                        txName.setEditable(true);
                    }
                } else if ((iNumber >= 96 & iNumber <= 105) | (iNumber >= 48 & iNumber <= 57) | (iNumber == 8)) {
                    txName.setEditable(true);
                } else {
                    txName.setEditable(false);
                }

            }
            if (txType.equals("N")) {

                if ((iNumber >= 96 & iNumber <= 105) | (iNumber >= 48 & iNumber <= 57) | (iNumber == 8)) {
                    txName.setEditable(true);
                } else {
                    txName.setEditable(false);
                }

            }
            if (txType.equals("A")) {

                if ((iNumber >= 65 & iNumber <= 90) | (iNumber == 8) | (iNumber == 32) | (iNumber == 46)) {
                    txName.setEditable(true);
                } else {
                    txName.setEditable(false);
                }

            }
            if (txType.equals("NA")) {

                if ((iNumber >= 96 & iNumber <= 105) | (iNumber >= 48 & iNumber <= 57) | (iNumber >= 65 & iNumber <= 90) | (iNumber == 8) | (iNumber == 45) | (iNumber == 32) | (iNumber == 44) | (iNumber == 46) | (iNumber == 47)) {
                    txName.setEditable(true);
                } else {
                    txName.setEditable(false);
                }

            }

        } else if ((iNumber == 8)) {
            txName.setEditable(true);
        } else {
            txName.setEditable(false);
        }
    }   
   
   private static final add add_ = new add();
    public static add getCallPopup() {
        return add_;
    }
 
    public void emterMouseClickMethod(){
    
        if (id_.getText().trim().isEmpty()) {
            id_.grabFocus();
        }else if (n1.getText().trim().isEmpty()) {
            n1.grabFocus();
        } else if (a1.getText().trim().isEmpty()) {
            a1.grabFocus();
        } else if (nic1.getText().trim().isEmpty()) {
            nic1.grabFocus();
        } else if (t1.getText().trim().isEmpty()) {
            t1.grabFocus();
        } else if (!(id_.getText().trim().isEmpty() & a1.getText().trim().isEmpty() &n1.getText().trim().isEmpty() & nic1.getText().trim().isEmpty() 
                & t1.getText().trim().isEmpty()) ) {
            idsearch = Integer.parseInt(id_.getText().trim());
            addDBTable();
        }
        
    }
    
    public void addDBTable(){
        try{
              try{   
 DBClass.putData("insert into pat_(name,address,nic,tell,wha) values('" + n1.getText()+ "','" + a1.getText() + "','" + nic1.getText() + "','" +  t1.getText()+ "','" + w1.getText()+ "')");
 DBClass.putData("insert into pat_(name,address,nic,tell,wha) values('" + n2.getText()+ "','" + a2.getText() + "','" + nic2.getText() + "','" +  t2.getText()+ "','" + w2.getText()+ "')");
 DBClass.putData("insert into pat_(name,address,nic,tell,wha) values('" + n3.getText()+ "','" + a3.getText() + "','" + nic3.getText() + "','" +  t3.getText()+ "','" + w3.getText()+ "')");
 DBClass.putData("insert into pat_(name,address,nic,tell,wha) values('" + n4.getText()+ "','" + a4.getText() + "','" + nic4.getText() + "','" +  t4.getText()+ "','" + w4.getText()+ "')");
 }catch(Exception ed){
        JOptionPane.showMessageDialog(null, "Error CouponInsert !!! \n"+ed, "Error Massage", JOptionPane.ERROR_MESSAGE);
 }
            
       DBClass.putData("insert into add_ (idadd,name1,address1,nic1,tell1,whatsapp1,"
               + "name2,address2,nic2,tell2,whatsapp2,"
               + "name3,address3,nic3,tell3,whatsapp3,"
               + "name4,address4,nic4,tell4,whatsapp4,"
               + "date,status) values("
               + "'" + idsearch + "' ,'" + n1.getText()+ "','" + a1.getText() + "' , '" + nic1.getText() + "' , '" +  Integer.parseInt(t1.getText().trim())+ "','" + w1.getText()+ "',"
               + "'" + n2.getText()+ "','" + a2.getText() + "' , '" + nic2.getText() + "' , '" + Integer.parseInt(t2.getText().trim())+ "','" + w2.getText()+ "',"
               + "'" + n3.getText()+ "','" + a3.getText() + "' , '" + nic3.getText() + "' , '" + Integer.parseInt(t3.getText().trim())+ "','" + w3.getText()+ "',"
               + "'" + n4.getText()+ "','" + a4.getText() + "' , '" + nic4.getText() + "' , '" + Integer.parseInt(t4.getText().trim())+ "','" + w4.getText()+ "',"
               + "'" + agent_la_date.getText() + "','1' )");
       
       
      
        JOptionPane.showConfirmDialog(null, "Coupon Added !!! \n", "Successfully", JOptionPane.OK_OPTION);
        cleareFields();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error CouponInsert !!! \n"+ex, "Error Massage", JOptionPane.ERROR_MESSAGE);
        id_.grabFocus();
        }
        
    }
    
    public void addJTable(){
    
    }
    
     private void cleareFields() {
        id_.setText(null);
        idsearch=0;
       n1.setText("Name1"); a1.setText("Address"); t1.setText("0000000000");nic1.setText("NIC");w1.setText("0000000000");
       n2.setText("Name2"); a2.setText("Address"); t2.setText("0000000000");nic2.setText("NIC");w2.setText("0000000000");
       n3.setText("Name3"); a3.setText("Address"); t3.setText("0000000000");nic3.setText("NIC");w3.setText("0000000000");
       n4.setText("Name4"); a4.setText("Address"); t4.setText("0000000000");nic4.setText("NIC");w4.setText("0000000000");
 searchEMP_tableadd();
    }
     
private void updateRX_idrx() {
        try {
            
DBClass.putData("update add_  set "
        + "name1='" + n1.getText() + "',address1='" + a1.getText() + "',nic1='" + nic1.getText()+ "',tell1='" + Integer.parseInt(t1.getText().trim()) + "',whatsapp1 ='" + w1.getText() + "',"
        + "name2='" + n2.getText() + "',address2='" + a2.getText() + "',nic2='" + nic2.getText()+ "',tell2='" +Integer.parseInt(t2.getText().trim()) + "',whatsapp2 ='" + w2.getText() + "',"
        + "name3='" + n3.getText() + "',address3='" + a3.getText() + "',nic3='" + nic3.getText()+ "',tell3='" +Integer.parseInt(t3.getText().trim()) + "',whatsapp3 ='" + w3.getText() + "',"
        + "name4='" + n4.getText() + "',address4='" + a4.getText() + "',nic4='" + nic4.getText()+ "',tell4='" + Integer.parseInt(t4.getText().trim()) + "',whatsapp4 ='" + w4.getText() + "'"
        + " where  idadd='" + idsearch + "' ");     
           
JOptionPane.showMessageDialog(this, "Update Successful", "Updated", JOptionPane.OK_OPTION);
            cleareFields();
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error ADDUpdate !!! \n "+e+" \n", "Error Massage", JOptionPane.ERROR_MESSAGE);
          id_.grabFocus();
        }
    }
     
    
 private void searchEMP() {
        try {
            DBClass.r = DBClass.getData("select * from add_ where idadd='" + idsearch + "' order by idadd");
            if (DBClass.r.isBeforeFirst() == true) {
                while (DBClass.r.next()) {
                   
                    n1.setText(DBClass.r.getString("name1"));
                    a1.setText(DBClass.r.getString("address1"));
                    nic1.setText(DBClass.r.getString("nic1"));
                    t1.setText(DBClass.r.getString("tell1"));
                    w1.setText(DBClass.r.getString("whatsapp1"));
                    
                    n2.setText(DBClass.r.getString("name2"));
                    a2.setText(DBClass.r.getString("address2"));
                    nic2.setText(DBClass.r.getString("nic2"));
                    t2.setText(DBClass.r.getString("tell2"));
                    w2.setText(DBClass.r.getString("whatsapp2"));
                    
                    n3.setText(DBClass.r.getString("name3"));
                    a3.setText(DBClass.r.getString("address3"));
                    nic3.setText(DBClass.r.getString("nic3"));
                    t3.setText(DBClass.r.getString("tell3"));
                    w3.setText(DBClass.r.getString("whatsapp3"));
                    
                    n4.setText(DBClass.r.getString("name4"));
                    a4.setText(DBClass.r.getString("address4"));
                    nic4.setText(DBClass.r.getString("nic4"));
                    t4.setText(DBClass.r.getString("tell4"));
                    w4.setText(DBClass.r.getString("whatsapp4"));

                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error ADDsearchEMPt !!! \n "+ex+" \n", "Error Massage", JOptionPane.ERROR_MESSAGE);
             id_.grabFocus();

        }
    }
 
 
 private void searchEMP_tableadd() {
        try {
            DBClass.r = DBClass.getData("select idadd,date from add_ where status='1' order by idadd");
            DefaultTableModel defTabMod = (DefaultTableModel) jTable1.getModel();
            defTabMod.getDataVector().removeAllElements();
           while (DBClass.r.next()) {
               Vector v = new Vector();
                    v.add(DBClass.r.getString("date"));
                    v.add(DBClass.r.getString("idadd"));
                 defTabMod.addRow(v);
                }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error ADDsearchEMPt !!! \n "+ex+" \n", "Error Massage", JOptionPane.ERROR_MESSAGE);
             id_.grabFocus();

        }
 }
 
 

}
