/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg01_1_siddha_system_1_4_1;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CHETHANA
 */
public class details extends javax.swing.JFrame {
UniversalMethod u = new UniversalMethod();
public static int idsearch,visi1,visi2,visi3,visi4,visi5,visi6,visi7,visi8,visi9,visi10,visi11,visi12,visi13;
    /**
     * Creates new form details
     */
    public details() {
        initComponents();
         u.imageMethod(background, home_la_uesr_image);
          UniversalMethod.TimeMethod(agent_la_date, agent_la_time);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        login_la_mini = new javax.swing.JLabel();
        login_la_cloce = new javax.swing.JLabel();
        agent_la_home_img = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        home_la_uesr_image = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        agent_la_time = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        agent_la_date = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tx_rx_id = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        n4 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        nic4 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        w4 = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        n2 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        nic2 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        w2 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        n3 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        nic3 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        w3 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel18 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        n1 = new javax.swing.JLabel();
        nic1 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        w1 = new javax.swing.JLabel();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel74 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel71 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1376, 768));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD COUPON");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(760, 1, 330, 40);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(0, 40, 1370, 10);

        login_la_mini.setBackground(new java.awt.Color(0, 0, 0));
        login_la_mini.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        login_la_mini.setForeground(new java.awt.Color(255, 255, 255));
        login_la_mini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_la_mini.setText("-");
        login_la_mini.setBorder(new javax.swing.border.MatteBorder(null));
        login_la_mini.setOpaque(true);
        login_la_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_la_miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_la_miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_la_miniMouseExited(evt);
            }
        });
        getContentPane().add(login_la_mini);
        login_la_mini.setBounds(1295, 10, 30, 30);

        login_la_cloce.setBackground(new java.awt.Color(0, 0, 0));
        login_la_cloce.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        login_la_cloce.setForeground(new java.awt.Color(255, 255, 255));
        login_la_cloce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_la_cloce.setText("x");
        login_la_cloce.setBorder(new javax.swing.border.MatteBorder(null));
        login_la_cloce.setOpaque(true);
        login_la_cloce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseExited(evt);
            }
        });
        getContentPane().add(login_la_cloce);
        login_la_cloce.setBounds(1330, 10, 30, 30);

        agent_la_home_img.setBackground(new java.awt.Color(0, 0, 0));
        agent_la_home_img.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        agent_la_home_img.setForeground(new java.awt.Color(255, 255, 255));
        agent_la_home_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agent_la_home_img.setText("Dash Board");
        agent_la_home_img.setOpaque(true);
        agent_la_home_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseExited(evt);
            }
        });
        getContentPane().add(agent_la_home_img);
        agent_la_home_img.setBounds(600, 5, 100, 30);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(580, 5, 20, 30);

        home_la_uesr_image.setForeground(new java.awt.Color(0, 0, 0));
        home_la_uesr_image.setText("userlogo");
        getContentPane().add(home_la_uesr_image);
        home_la_uesr_image.setBounds(290, 10, 30, 30);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(280, 5, 20, 30);

        agent_la_time.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agent_la_time.setForeground(new java.awt.Color(255, 255, 255));
        agent_la_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agent_la_time.setText("Invoice");
        agent_la_time.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(agent_la_time);
        agent_la_time.setBounds(150, 5, 130, 35);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(140, 5, 20, 30);

        agent_la_date.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agent_la_date.setForeground(new java.awt.Color(255, 255, 255));
        agent_la_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agent_la_date.setText("Invoice");
        agent_la_date.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(agent_la_date);
        agent_la_date.setBounds(10, 5, 130, 35);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Refresh");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 160, 40);

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rc ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(220, 60, 190, 130);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Coupon ID");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(430, 80, 110, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(":");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(540, 80, 20, 30);

        tx_rx_id.setBackground(new java.awt.Color(255, 255, 255));
        tx_rx_id.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_rx_id.setForeground(new java.awt.Color(0, 0, 0));
        tx_rx_id.setText(" ");
        tx_rx_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_rx_idKeyPressed(evt);
            }
        });
        getContentPane().add(tx_rx_id);
        tx_rx_id.setBounds(560, 80, 170, 33);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("11");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jLabel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel3KeyTyped(evt);
            }
        });
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(430, 70, 60, 50);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("12");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(510, 10, 60, 50);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("13");
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jLabel7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel7KeyPressed(evt);
            }
        });
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(510, 70, 60, 50);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("10");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(430, 10, 60, 50);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("8");
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jLayeredPane1.add(jLabel9);
        jLabel9.setBounds(350, 10, 60, 50);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("9");
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(350, 70, 60, 50);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("6");
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(270, 10, 60, 50);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("4");
        jLabel12.setOpaque(true);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jLayeredPane1.add(jLabel12);
        jLabel12.setBounds(190, 10, 60, 50);

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("2");
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        jLayeredPane1.add(jLabel13);
        jLabel13.setBounds(20, 70, 60, 50);

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("3");
        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        jLayeredPane1.add(jLabel14);
        jLabel14.setBounds(100, 40, 60, 50);

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("5");
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jLayeredPane1.add(jLabel15);
        jLabel15.setBounds(190, 70, 60, 50);

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("7");
        jLabel16.setOpaque(true);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        jLayeredPane1.add(jLabel16);
        jLabel16.setBounds(270, 70, 60, 50);

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("1");
        jLabel17.setOpaque(true);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });
        jLayeredPane1.add(jLabel17);
        jLabel17.setBounds(20, 10, 60, 50);

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jLayeredPane1.add(jSeparator9);
        jSeparator9.setBounds(170, 10, 10, 110);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(770, 60, 590, 130);

        jLayeredPane4.setBackground(new java.awt.Color(144, 215, 144));
        jLayeredPane4.setOpaque(true);

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Name 04");
        jLayeredPane4.add(jLabel33);
        jLabel33.setBounds(20, 10, 90, 30);

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Address");
        jLayeredPane4.add(jLabel34);
        jLabel34.setBounds(20, 40, 90, 30);

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("NIC");
        jLayeredPane4.add(jLabel35);
        jLabel35.setBounds(20, 70, 90, 30);

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Tell");
        jLayeredPane4.add(jLabel36);
        jLabel36.setBounds(20, 100, 90, 30);

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Whatsapp");
        jLayeredPane4.add(jLabel37);
        jLabel37.setBounds(20, 130, 90, 30);

        n4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n4.setForeground(new java.awt.Color(0, 0, 0));
        n4.setText("Name 01");
        jLayeredPane4.add(n4);
        n4.setBounds(130, 10, 420, 30);

        a4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        a4.setForeground(new java.awt.Color(0, 0, 0));
        a4.setText("11111111111111111111111111111111111111111111111111111111111111111");
        jLayeredPane4.add(a4);
        a4.setBounds(130, 40, 460, 30);

        nic4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nic4.setForeground(new java.awt.Color(0, 0, 0));
        nic4.setText("Name 01");
        jLayeredPane4.add(nic4);
        nic4.setBounds(130, 70, 200, 30);

        t4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        t4.setForeground(new java.awt.Color(0, 0, 0));
        t4.setText("Name 01");
        jLayeredPane4.add(t4);
        t4.setBounds(130, 100, 200, 30);

        w4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        w4.setForeground(new java.awt.Color(0, 0, 0));
        w4.setText("Name 01");
        jLayeredPane4.add(w4);
        w4.setBounds(130, 130, 200, 30);

        getContentPane().add(jLayeredPane4);
        jLayeredPane4.setBounds(730, 570, 600, 180);

        jLayeredPane5.setBackground(new java.awt.Color(144, 215, 144));
        jLayeredPane5.setOpaque(true);

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Name 02");
        jLayeredPane5.add(jLabel23);
        jLabel23.setBounds(20, 10, 90, 30);

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Address");
        jLayeredPane5.add(jLabel24);
        jLabel24.setBounds(20, 40, 90, 30);

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("NIC");
        jLayeredPane5.add(jLabel25);
        jLabel25.setBounds(20, 70, 90, 30);

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Tell");
        jLayeredPane5.add(jLabel26);
        jLabel26.setBounds(20, 100, 90, 30);

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Whatsapp");
        jLayeredPane5.add(jLabel27);
        jLabel27.setBounds(20, 130, 90, 30);

        n2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n2.setForeground(new java.awt.Color(0, 0, 0));
        n2.setText("Name 01");
        jLayeredPane5.add(n2);
        n2.setBounds(130, 10, 420, 30);

        a2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        a2.setForeground(new java.awt.Color(0, 0, 0));
        a2.setText("11111111111111111111111111111111111111111111111111111111111111111");
        jLayeredPane5.add(a2);
        a2.setBounds(130, 40, 460, 30);

        nic2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nic2.setForeground(new java.awt.Color(0, 0, 0));
        nic2.setText("Name 01");
        jLayeredPane5.add(nic2);
        nic2.setBounds(130, 70, 200, 30);

        t2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        t2.setForeground(new java.awt.Color(0, 0, 0));
        t2.setText("Name 01");
        jLayeredPane5.add(t2);
        t2.setBounds(130, 100, 200, 30);

        w2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        w2.setForeground(new java.awt.Color(0, 0, 0));
        w2.setText("Name 01");
        jLayeredPane5.add(w2);
        w2.setBounds(130, 130, 200, 30);

        getContentPane().add(jLayeredPane5);
        jLayeredPane5.setBounds(730, 370, 600, 180);

        jLayeredPane3.setBackground(new java.awt.Color(144, 215, 144));
        jLayeredPane3.setOpaque(true);

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Name 03");
        jLayeredPane3.add(jLabel28);
        jLabel28.setBounds(20, 10, 90, 30);

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Address");
        jLayeredPane3.add(jLabel29);
        jLabel29.setBounds(20, 40, 90, 30);

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("NIC");
        jLayeredPane3.add(jLabel30);
        jLabel30.setBounds(20, 70, 90, 30);

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Tell");
        jLayeredPane3.add(jLabel31);
        jLabel31.setBounds(20, 100, 90, 30);

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Whatsapp");
        jLayeredPane3.add(jLabel32);
        jLabel32.setBounds(20, 130, 90, 30);

        n3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n3.setForeground(new java.awt.Color(0, 0, 0));
        n3.setText("Name 01");
        jLayeredPane3.add(n3);
        n3.setBounds(130, 10, 420, 30);

        a3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        a3.setForeground(new java.awt.Color(0, 0, 0));
        a3.setText("11111111111111111111111111111111111111111111111111111111111111111");
        jLayeredPane3.add(a3);
        a3.setBounds(130, 40, 460, 30);

        nic3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nic3.setForeground(new java.awt.Color(0, 0, 0));
        nic3.setText("Name 01");
        jLayeredPane3.add(nic3);
        nic3.setBounds(130, 70, 200, 30);

        t3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        t3.setForeground(new java.awt.Color(0, 0, 0));
        t3.setText("Name 01");
        jLayeredPane3.add(t3);
        t3.setBounds(130, 100, 200, 30);

        w3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        w3.setForeground(new java.awt.Color(0, 0, 0));
        w3.setText("Name 01");
        jLayeredPane3.add(w3);
        w3.setBounds(130, 130, 200, 30);

        getContentPane().add(jLayeredPane3);
        jLayeredPane3.setBounds(70, 570, 600, 180);

        jLayeredPane2.setBackground(new java.awt.Color(144, 215, 144));
        jLayeredPane2.setOpaque(true);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Whatsapp");
        jLayeredPane2.add(jLabel18);
        jLabel18.setBounds(20, 130, 90, 30);

        a1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        a1.setForeground(new java.awt.Color(0, 0, 0));
        a1.setText("11111111111111111111111111111111111111111111111111111111111111111");
        jLayeredPane2.add(a1);
        a1.setBounds(130, 40, 460, 30);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Address");
        jLayeredPane2.add(jLabel20);
        jLabel20.setBounds(20, 40, 90, 30);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("NIC");
        jLayeredPane2.add(jLabel21);
        jLabel21.setBounds(20, 70, 90, 30);

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Tell");
        jLayeredPane2.add(jLabel22);
        jLabel22.setBounds(20, 100, 90, 30);

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Name 01");
        jLayeredPane2.add(jLabel38);
        jLabel38.setBounds(20, 10, 90, 30);

        n1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n1.setForeground(new java.awt.Color(0, 0, 0));
        n1.setText("Name 01");
        jLayeredPane2.add(n1);
        n1.setBounds(130, 10, 420, 30);

        nic1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nic1.setForeground(new java.awt.Color(0, 0, 0));
        nic1.setText("Name 01");
        jLayeredPane2.add(nic1);
        nic1.setBounds(130, 70, 200, 30);

        t1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        t1.setForeground(new java.awt.Color(0, 0, 0));
        t1.setText("Name 01");
        jLayeredPane2.add(t1);
        t1.setBounds(130, 100, 200, 30);

        w1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        w1.setForeground(new java.awt.Color(0, 0, 0));
        w1.setText("Name 01");
        jLayeredPane2.add(w1);
        w1.setBounds(130, 130, 200, 30);

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(70, 370, 600, 180);

        jLayeredPane6.setBackground(new java.awt.Color(108, 88, 141));
        jLayeredPane6.setOpaque(true);

        jLabel66.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 0, 0));
        jLabel66.setText("Coupon");
        jLayeredPane6.add(jLabel66);
        jLabel66.setBounds(10, 10, 60, 30);

        jLabel67.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 0, 0));
        jLabel67.setText("Name ");
        jLayeredPane6.add(jLabel67);
        jLabel67.setBounds(10, 40, 60, 30);

        jLabel68.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(0, 0, 0));
        jLabel68.setText("Date");
        jLayeredPane6.add(jLabel68);
        jLabel68.setBounds(10, 70, 60, 30);

        jLabel69.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 0, 0));
        jLabel69.setText("Time");
        jLayeredPane6.add(jLabel69);
        jLabel69.setBounds(10, 100, 60, 30);

        jLabel70.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 0, 0));
        jLabel70.setText("Name 01");
        jLayeredPane6.add(jLabel70);
        jLabel70.setBounds(110, 100, 190, 30);

        jLabel72.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 0, 0));
        jLabel72.setText("Name 01");
        jLayeredPane6.add(jLabel72);
        jLabel72.setBounds(110, 10, 190, 30);

        jLabel73.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(0, 0, 0));
        jLabel73.setText("Name 01");
        jLayeredPane6.add(jLabel73);
        jLabel73.setBounds(110, 70, 190, 30);

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jLayeredPane6.add(jComboBox1);
        jComboBox1.setBounds(100, 40, 360, 30);

        jLabel74.setBackground(new java.awt.Color(0, 0, 0));
        jLabel74.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel74.setText("Save");
        jLabel74.setOpaque(true);
        jLabel74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel74MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel74MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel74MouseExited(evt);
            }
        });
        jLayeredPane6.add(jLabel74);
        jLabel74.setBounds(420, 100, 130, 30);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Type");
        jLayeredPane6.add(jLabel19);
        jLabel19.setBounds(450, 0, 90, 30);

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Type");
        jLayeredPane6.add(jLabel39);
        jLabel39.setBounds(380, 0, 33, 30);

        getContentPane().add(jLayeredPane6);
        jLayeredPane6.setBounds(770, 210, 590, 140);

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setForeground(new java.awt.Color(0, 0, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient", "Type", "Date", "Time", "C.Number"
            }
        ));
        jScrollPane1.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(1).setMinWidth(100);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(100);
            jTable2.getColumnModel().getColumn(2).setMinWidth(100);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable2.getColumnModel().getColumn(3).setMinWidth(100);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable2.getColumnModel().getColumn(4).setMinWidth(100);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 200, 690, 150);

        jLabel71.setBackground(new java.awt.Color(0, 0, 0));
        jLabel71.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("New");
        jLabel71.setOpaque(true);
        jLabel71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel71MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel71MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel71MouseExited(evt);
            }
        });
        getContentPane().add(jLabel71);
        jLabel71.setBounds(30, 150, 160, 40);

        jLabel75.setBackground(new java.awt.Color(0, 0, 0));
        jLabel75.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("Search");
        jLabel75.setOpaque(true);
        jLabel75.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel75MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel75MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel75MouseExited(evt);
            }
        });
        getContentPane().add(jLabel75);
        jLabel75.setBounds(30, 100, 160, 40);

        background.setBackground(new java.awt.Color(234, 232, 232));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 1380, 770);

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(0, 360, 1370, 10);

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(740, 50, 10, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_la_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseClicked
        m( login_la_mini,2); //
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_login_la_miniMouseClicked

    private void login_la_miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseEntered
        //    login_la_mini.setBackground(Color.gray);
        m( login_la_mini,0); //  u.imageMethod("/img/mini2.png", login_la_mini);
    }//GEN-LAST:event_login_la_miniMouseEntered

    private void login_la_miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseExited
        //    login_la_mini.setBackground(Color.white);
        m( login_la_mini,1); //   u.imageMethod("/img/mini.png", login_la_mini);
    }//GEN-LAST:event_login_la_miniMouseExited

    private void login_la_cloceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseClicked
        m( login_la_cloce,2); //
        SystemClose();
    }//GEN-LAST:event_login_la_cloceMouseClicked

    private void login_la_cloceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseEntered
        //    login_la_cloce.setBackground(Color.red);
        m( login_la_cloce,0); //   u.imageMethod("/img/exti.png", login_la_cloce);
    }//GEN-LAST:event_login_la_cloceMouseEntered

    private void login_la_cloceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseExited
        //    login_la_cloce.setBackground(Color.white);
        m( login_la_cloce,1); //   u.imageMethod("/img/exti2.png", login_la_cloce);
    }//GEN-LAST:event_login_la_cloceMouseExited

    private void agent_la_home_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseClicked
        m(agent_la_home_img,2);
        int x = JOptionPane.showConfirmDialog(this, "Do you sure Go to The Home ?", "Change Interface", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.YES_OPTION == x) {
                dashboard.getCallPopup().setVisible(true);
                this.dispose();
            } else if (JOptionPane.NO_OPTION == x) {
                setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                tx_rx_id.grabFocus();
            }
        
    }//GEN-LAST:event_agent_la_home_imgMouseClicked

    private void agent_la_home_imgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseEntered
        m(agent_la_home_img,0); //  u.imageMethod("/img/homeB2.png", agent_la_home_img);
    }//GEN-LAST:event_agent_la_home_imgMouseEntered

    private void agent_la_home_imgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseExited
        m(agent_la_home_img,1); //    u.imageMethod("/img/homeB1.png", agent_la_home_img);
    }//GEN-LAST:event_agent_la_home_imgMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        m(jLabel2,2);
        searchEMP_tableadd();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        m(jLabel2,0); //   u.imageMethod("/img/rf2.png", jLabel2);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        m(jLabel2,1); // u.imageMethod("/img/rf.png", jLabel2);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel defTabMod = (DefaultTableModel) jTable1.getModel();
        idsearch = Integer.parseInt(defTabMod.getValueAt(jTable1.getSelectedRow(), 0).toString());
        tx_rx_id.setText(""+idsearch);
        patientr_howmutch(); 
        searchEMP();
      cOU_vISIBLE();
         
    }//GEN-LAST:event_jTable1MouseClicked

    private void tx_rx_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_rx_idKeyPressed
        
        txValidateKeyEvent(evt, tx_rx_id, "N", 9);
        
    }//GEN-LAST:event_tx_rx_idKeyPressed

    private void jLabel75MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel75MouseClicked
       m(jLabel75,2); //
      if (!tx_rx_id.getText().isEmpty()) {
            idsearch = Integer.parseInt(tx_rx_id.getText());
             searchEMP();
             patientr_howmutch();
             cOU_vISIBLE();
            
        } else {
            JOptionPane.showMessageDialog(null, "Error Not Selected The ID  !!! \n searchEMP() \n" , "Error Massage", JOptionPane.ERROR_MESSAGE);
            tx_rx_id.grabFocus();
        }
    }//GEN-LAST:event_jLabel75MouseClicked

    private void jLabel75MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel75MouseEntered
      m (jLabel75,0); //
    }//GEN-LAST:event_jLabel75MouseEntered

    private void jLabel75MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel75MouseExited
      m(jLabel75,1); //
    }//GEN-LAST:event_jLabel75MouseExited

    private void jLabel71MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel71MouseClicked
     m(jLabel71,2); //
     cleareFields();
      DefaultTableModel defTabMod = (DefaultTableModel) jTable2.getModel();
         defTabMod.setRowCount(0);
    }//GEN-LAST:event_jLabel71MouseClicked

    private void jLabel71MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel71MouseEntered
       m(jLabel71,0); //
    }//GEN-LAST:event_jLabel71MouseEntered

    private void jLabel71MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel71MouseExited
          m(jLabel71,1); //
    }//GEN-LAST:event_jLabel71MouseExited

    private void jLabel74MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel74MouseClicked
         m(jLabel74,2); //
         coPSave();
    }//GEN-LAST:event_jLabel74MouseClicked

    private void jLabel74MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel74MouseEntered
        m(jLabel74,0); //
    }//GEN-LAST:event_jLabel74MouseEntered

    private void jLabel74MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel74MouseExited
        m(jLabel74,1); //
    }//GEN-LAST:event_jLabel74MouseExited

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
     if(visi1==0){
         m(jLabel17,4);
     }
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        if(visi1==0){ 
            m(jLabel17,1);
        }
    }//GEN-LAST:event_jLabel17MouseExited

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
     if(visi1==0){
         m(jLabel17,5);
       jLabel72.setText("1");
       jLabel73.setText(agent_la_date.getText());
       jLabel70.setText(agent_la_time.getText());
       jLabel19.setText("OPD");
     }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
      if(visi2==0){
          m(jLabel13,5);
      jLabel72.setText("2");
       jLabel73.setText(agent_la_date.getText());
       jLabel70.setText(agent_la_time.getText());
       jLabel19.setText("OPD");
      }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
       if(visi2==0){
           m(jLabel13,4);
       }
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
       if(visi2==0){
           m(jLabel13,1);
       }
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
       if(visi3==0){
        m(jLabel14,5);
       jLabel72.setText("3");
       jLabel73.setText(agent_la_date.getText());
       jLabel70.setText(agent_la_time.getText());
       jLabel19.setText("OPD");}
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        if(visi3==0){ 
            m(jLabel14,4);
        }
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
     if(visi3==0){
         m(jLabel14,1);
     }
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
     if(visi4==0){
        m(jLabel12,5);
       jLabel72.setText("4");
       jLabel73.setText(agent_la_date.getText());
       jLabel70.setText(agent_la_time.getText());
       jLabel19.setText("Clinick");}
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
       if(visi4==0){
           m(jLabel12,4);
       }
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
     if(visi4==0){
         m(jLabel12,1);
     }
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
      if(visi6==0){
        m(jLabel11,5);
       jLabel72.setText("6");
       jLabel73.setText(agent_la_date.getText());
       jLabel70.setText(agent_la_time.getText());
        jLabel19.setText("Clinick");}
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
      if(visi6==0){
          m(jLabel11,4);
      }
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
      if(visi6==0){
          m(jLabel11,1);
      }
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
       if(visi5==0){ 
        m(jLabel15,5);
       jLabel72.setText("5");
       jLabel73.setText(agent_la_date.getText());
       jLabel70.setText(agent_la_time.getText());
        jLabel19.setText("Clinick");}
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
     if(visi5==0){  
         m(jLabel15,4);
     }
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
       if(visi5==0){ 
           m(jLabel15,1);
       }
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
      if(visi7==0){
        m(jLabel16,5);
       jLabel72.setText("7");
       jLabel73.setText(agent_la_date.getText());
       jLabel70.setText(agent_la_time.getText());
        jLabel19.setText("Clinick");}
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        if(visi7==0){ 
            m(jLabel16,4);
        }
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        if(visi7==0){
            m(jLabel16,1);
        }
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
     if(visi8==0){ 
        m(jLabel9,5);
       jLabel72.setText("8");
       jLabel73.setText(agent_la_date.getText());
       jLabel70.setText(agent_la_time.getText());}
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        if(visi8==0){ 
            m(jLabel9,4);
        }//
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
       if(visi8==0){ 
           m(jLabel9,1);
       }//  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       if(visi9==0){
        m(jLabel10,5);
       jLabel72.setText("9");
       jLabel73.setText(agent_la_date.getText());
       jLabel70.setText(agent_la_time.getText());
        jLabel19.setText("Clinick");}
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
       if(visi9==0){ 
           m(jLabel10,4);
       }
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
       if(visi9==0){
           m(jLabel10,1);
       }
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
      if(visi10==0){
        m(jLabel8,5);
       jLabel72.setText("10");
       jLabel73.setText(agent_la_date.getText());
       jLabel70.setText(agent_la_time.getText());}
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
    if(visi10==0){
        m(jLabel8,4);
    }
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
      if(visi10==0){
          m(jLabel8,1);
      }
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3KeyPressed
       
    }//GEN-LAST:event_jLabel3KeyPressed

    private void jLabel3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3KeyReleased

    private void jLabel3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3KeyTyped

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
      if(visi12==0){
        m(jLabel6,5);
       jLabel72.setText("12");
       jLabel73.setText(agent_la_date.getText());
       jLabel70.setText(agent_la_time.getText());
        jLabel19.setText("Clinick");}
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
     if(visi12==0){
         m(jLabel6,4);
     }
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
      if(visi12==0){
          m(jLabel6,1);
      }
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel7KeyPressed
       
    }//GEN-LAST:event_jLabel7KeyPressed

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
       if(visi13==0){
           m(jLabel7,4);
       }
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
      if(visi13==0){
        m(jLabel7,5);
       jLabel72.setText("13");
       jLabel73.setText(agent_la_date.getText());
       jLabel70.setText(agent_la_time.getText());
        jLabel19.setText("Clinick");}
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
       if(visi13==0){
           m(jLabel7,1);
       }
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
     if(visi11==0){
        m(jLabel3,5);
       jLabel72.setText("11");
       jLabel73.setText(agent_la_date.getText());
       jLabel70.setText(agent_la_time.getText());
        jLabel19.setText("Clinick");}
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
       if(visi11==0){
           m(jLabel3,4);
       }
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
       if(visi11==0){
           m(jLabel3,1);
       }
    }//GEN-LAST:event_jLabel3MouseExited

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new details().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel agent_la_date;
    private javax.swing.JLabel agent_la_home_img;
    private javax.swing.JLabel agent_la_time;
    private javax.swing.JLabel background;
    private javax.swing.JLabel home_la_uesr_image;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel login_la_cloce;
    private javax.swing.JLabel login_la_mini;
    private javax.swing.JLabel n1;
    private javax.swing.JLabel n2;
    private javax.swing.JLabel n3;
    private javax.swing.JLabel n4;
    private javax.swing.JLabel nic1;
    private javax.swing.JLabel nic2;
    private javax.swing.JLabel nic3;
    private javax.swing.JLabel nic4;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JTextField tx_rx_id;
    private javax.swing.JLabel w1;
    private javax.swing.JLabel w2;
    private javax.swing.JLabel w3;
    private javax.swing.JLabel w4;
    // End of variables declaration//GEN-END:variables
 public void m(JLabel lable,int T){
    if(T==0){//en
     lable.setBackground(new Color(255, 170, 0));
    }else if(T==1){//ex
        lable.setBackground(new Color(0, 0, 0));
    }else if(T==2){//cl
        lable.setBackground(new Color(0, 255, 251));
    }else if(T==3){
        lable.setBackground(new Color(144,215,144));//[144,215,144]
    }else if(T==4){
        lable.setBackground(new Color(51,255,51));//[51,255,51] //kola
    }else if(T==5){
        lable.setBackground(Color.RED);// // rathu
    }
 }   
private void txValidateKeyEvent(KeyEvent evt, JTextField txName, String txType, int lenthNeedFeld) {

        int iNumber = evt.getKeyCode();
        if (txName.getText().length() <= lenthNeedFeld) {
            
            if (txType.equals("N")) {

                if ((iNumber >= 96 & iNumber <= 105) | (iNumber >= 48 & iNumber <= 57) | (iNumber == 8)) {
                    txName.setEditable(true);
                } else {
                    txName.setEditable(false);
                }

            }
            if (txType.equals("A")) {

                if ((iNumber >= 65 & iNumber <= 90) | (iNumber == 8) | (iNumber == 32) | (iNumber == 46)) {
                    txName.setEditable(true);
                } else {
                    txName.setEditable(false);
                }

            }
            if (txType.equals("NA")) {

                if ((iNumber >= 96 & iNumber <= 105) | (iNumber >= 48 & iNumber <= 57) | (iNumber >= 65 & iNumber <= 90) | (iNumber == 8) | (iNumber == 45) | (iNumber == 32) | (iNumber == 44) | (iNumber == 46) | (iNumber == 47)) {
                    txName.setEditable(true);
                } else {
                    txName.setEditable(false);
                }

            }

        } else if ((iNumber == 8)) {
            txName.setEditable(true);
        } else {
            txName.setEditable(false);
        }
    }

   void SystemClose() {
        int x = JOptionPane.showConfirmDialog(this, "Do you sure close the System ?", "Exit System", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == x) {
            // setDefaultCloseOperation(EXIT_ON_CLOSE);
            System.exit(0);
        } else if (JOptionPane.NO_OPTION == x) {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            login_la_cloce.setBackground(new Color(153, 204, 255));
        }
    }
   
   private static final details details_ = new details();
    public static details getCallPopup() {
        return details_;
    }
   
    
     private void searchEMP_tableadd() {
        try {
            DBClass.getData("select idadd from add_ where status='1' order by idadd");
            DefaultTableModel defTabMod = (DefaultTableModel) jTable1.getModel();
            defTabMod.getDataVector().removeAllElements();
           while (DBClass.r.next()) {
               Vector v = new Vector();
                    v.add(DBClass.r.getString("idadd"));
                 defTabMod.addRow(v);
                }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error ADDsearchEMPt !!! \n "+ex+" \n", "Error Massage", JOptionPane.ERROR_MESSAGE);
             tx_rx_id.grabFocus();

        }
 }
   
   private void searchEMP() {
        try {
            DBClass.r = DBClass.getData("select * from add_ where idadd='" + idsearch + "' order by idadd");
            if (DBClass.r.isBeforeFirst() == true) {
                while (DBClass.r.next()) {
                   
                    n1.setText(DBClass.r.getString("name1"));
                    a1.setText(DBClass.r.getString("address1"));
                    nic1.setText(DBClass.r.getString("nic1"));
                    t1.setText(DBClass.r.getString("tell1"));
                    w1.setText(DBClass.r.getString("whatsapp1"));
                    
                    n2.setText(DBClass.r.getString("name2"));
                    a2.setText(DBClass.r.getString("address2"));
                    nic2.setText(DBClass.r.getString("nic2"));
                    t2.setText(DBClass.r.getString("tell2"));
                    w2.setText(DBClass.r.getString("whatsapp2"));
                    
                    n3.setText(DBClass.r.getString("name3"));
                    a3.setText(DBClass.r.getString("address3"));
                    nic3.setText(DBClass.r.getString("nic3"));
                    t3.setText(DBClass.r.getString("tell3"));
                    w3.setText(DBClass.r.getString("whatsapp3"));
                    
                    n4.setText(DBClass.r.getString("name4"));
                    a4.setText(DBClass.r.getString("address4"));
                    nic4.setText(DBClass.r.getString("nic4"));
                    t4.setText(DBClass.r.getString("tell4"));
                    w4.setText(DBClass.r.getString("whatsapp4"));

           
                }
                 jComboBox1.removeAllItems();     
            jComboBox1.addItem(n1.getText());
             jComboBox1.addItem(n2.getText());
              jComboBox1.addItem(n3.getText());
               jComboBox1.addItem(n4.getText());
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error searchEMP !!! \n "+ex+" \n", "Error Massage", JOptionPane.ERROR_MESSAGE);
             tx_rx_id.grabFocus();

        }
    }  
   
   
   private void cleareFields() {
       
         
        tx_rx_id.setText(null);
        idsearch=0;
       n1.setText("Name1"); a1.setText("Address"); t1.setText("0000000000");nic1.setText("NIC");w1.setText("0000000000");
       n2.setText("Name2"); a2.setText("Address"); t2.setText("0000000000");nic2.setText("NIC");w2.setText("0000000000");
       n3.setText("Name3"); a3.setText("Address"); t3.setText("0000000000");nic3.setText("NIC");w3.setText("0000000000");
       n4.setText("Name4"); a4.setText("Address"); t4.setText("0000000000");nic4.setText("NIC");w4.setText("0000000000");
               jComboBox1.removeAllItems();
            jComboBox1.addItem("Not Selected");
            
       jLabel72.setText(null);
        jLabel73.setText(null);
        jLabel70.setText(null);
         jLabel19.setText(null);
         
         visi1=0;visi2=0;visi3=0;visi4=0;visi5=0;visi6=0;visi7=0;visi8=0;visi9=0;visi10=0;visi11=0;visi12=0;visi13=0;
        
         jLabel17.setEnabled(true);m(jLabel17,1);
         jLabel13.setEnabled(true); m(jLabel13,1);
         jLabel14.setEnabled(true); m(jLabel14,1);
         jLabel12.setEnabled(true);m(jLabel12,1);
         jLabel15.setEnabled(true);m(jLabel15,1);
         jLabel11.setEnabled(true);m(jLabel11,1);
         jLabel16.setEnabled(true);m(jLabel16,1);
         jLabel9.setEnabled(true); m(jLabel9,1);
         jLabel10.setEnabled(true);m(jLabel10,1);
         jLabel8.setEnabled(true);m(jLabel8,1);
         jLabel3.setEnabled(true);m(jLabel3,1);
         jLabel6.setEnabled(true);m(jLabel6,1);
         jLabel7.setEnabled(true); m(jLabel7,1);
                       
 searchEMP_tableadd();
    }  
   
   
   
    public void coPSave(){
       
         int x = JOptionPane.showConfirmDialog(this, "Do you sure Get Coupon ?", "Conform !", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == x) {
            try{         
 DBClass.putData("insert into ccopon (idadd,cnumber,type,patient,date,time,status) values('" + Integer.parseInt(tx_rx_id.getText())+ "','" +Integer.parseInt(jLabel72.getText()) +
         "','" + jLabel19.getText() + "','" +  jComboBox1.getSelectedItem().toString()+ "','" + jLabel73.getText()+ "','" + jLabel70.getText()+ "','1')");
 
 cOU_vISIBLE();
 patientr_howmutch();
        JOptionPane.showConfirmDialog(null, "Coupon Added !!! \n", "Successfully", JOptionPane.OK_OPTION);
        cleareFields();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error coPSave !!! \n"+ex, "Error Massage", JOptionPane.ERROR_MESSAGE);
        tx_rx_id.grabFocus();
        }
            
        } else if (JOptionPane.NO_OPTION == x) {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            tx_rx_id.grabFocus();
        }
    
    }
   
    public void cOU_vISIBLE(){
        try {
            DBClass.getData("select * from ccopon where idadd='" + idsearch + "' order by idccopon");
            if (DBClass.r.isBeforeFirst() == true) {
                while (DBClass.r.next()) {
                   int x = DBClass.r.getInt("cnumber");
                   if(DBClass.r.getInt("status")==1){
                       if(x==1){
                          m(jLabel17,5);jLabel17.setEnabled(false); visi1=1;
                       }if(x==2){
                          m(jLabel13,5);jLabel13.setEnabled(false); visi2=1;
                       }if(x==3){
                          m(jLabel14,5);jLabel14.setEnabled(false); visi3=1;
                       }if(x==4){
                          m(jLabel12,5);jLabel12.setEnabled(false); visi4=1;
                       }if(x==5){
                          m(jLabel15,5);jLabel15.setEnabled(false); visi5=1;
                       }if(x==6){
                          m(jLabel11,5);jLabel11.setEnabled(false); visi6=1;
                       }if(x==7){
                          m(jLabel16,5);jLabel16.setEnabled(false); visi7=1;
                       }if(x==8){
                          m(jLabel9,5);jLabel9.setEnabled(false); visi8=1;
                       }if(x==9){
                          m(jLabel10,5);jLabel10.setEnabled(false); visi9=1;
                       }if(x==10){
                          m(jLabel8,5);jLabel8.setEnabled(false); visi10=1;
                       }if(x==11){
                          m(jLabel3,5);jLabel3.setEnabled(false); visi11=1;
                       }if(x==12){
                          m(jLabel6,5);jLabel6.setEnabled(false); visi12=1;
                       }if(x==13){
                          m(jLabel7,5);jLabel7.setEnabled(false); visi13=1;
                       }
                   }
                   
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error cOU_vISIBLE !!! \n "+ex+" \n", "Error Massage", JOptionPane.ERROR_MESSAGE);
             tx_rx_id.grabFocus();

        }
    } 
    
    
     public void patientr_howmutch(){
        try {
            DefaultTableModel defTabMod = (DefaultTableModel) jTable2.getModel();
            defTabMod.getDataVector().removeAllElements();
            DBClass.getData("select * from ccopon where idadd='"+Integer.parseInt(tx_rx_id.getText()) +"' order by idccopon");
            if (DBClass.r.isBeforeFirst() == true) {
                while (DBClass.r.next()) {
                  Vector v = new Vector();
                    v.add(DBClass.r.getString("patient"));
                    v.add(DBClass.r.getString("type"));
                    v.add(DBClass.r.getString("date"));
                    v.add(DBClass.r.getString("time"));
                    v.add(DBClass.r.getString("cnumber"));
                   defTabMod.addRow(v);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error cOU_vISIBLE !!! \n "+ex+" \n", "Error Massage", JOptionPane.ERROR_MESSAGE);
             tx_rx_id.grabFocus();

        }
        
    }  
    
    
    
}
